### ISSUE TITLE
Client zeigt falschen Code an

### ISSUE THREAD

**Issue by ba-lindner** [niklas-simon/PI22_Brainfuck-Interpreter#2]
Der Client zeigt beim Digital Twin den Code mit Kommentaren an (Endpunkt `/api/{run|sse}/code`).
Da der Raspberry Kommentare rausfiltert, sollte beim Digital Twin der Code ohne Kommentare angezeit werden.
Dazu sollte der Code aus dem Endpunkt `/api/{run|sse}/state` verwendet werden:
```json
{
    "code": {
        "fragment": ">>+++",
        "offset": 0,
        "pc": 1
    }
}
```

**Comment by niklas-simon** [comment]
@ba-lindner review please

**Comment by niklas-simon** [comment]
könntest du mir, falls schon ein Programm da ist, es im state mit schicken, selbst wenn der Interpreter auf "idle" steht?

**Comment by ba-lindner** [comment]
mit 78dc6c wird der Code jetzt auch in states != running an den client mitgeteilt.
